name: CI
on:
  - push
  - pull_request
jobs:
  test:
    name: Node ${{ matrix.node-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        node-version:
          - 15
          - 14
          - 13
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
    steps:
      # checkout code
      - name: Checkout Code
        uses: actions/checkout@v2

      - uses: actions/setup-node@v2

      # Install node from package.json volta config
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      # Install packages
      - name: Install NPM Packages
        run: yarn


      # Lint
      - name: Run Linting
        run: yarn lint


      - name: Build
        run: yarn build:ci
